import type { EditorialLocale } from "../catalog/editorial-catalogue";

/** Translations of existing English copy only; HU/KO await LP editorial review. */
export const marketingCopy = {
  en: {
    hero: { eyebrow: "Trusted Korean Skincare", heading: "Feel confident in your skin.", description: "Starting in Hungary, growing across Europe — HanaPure carefully selects authentic Korean skincare with real skin benefits and trusted guidance.", shop: "Shop Korean Skincare", routine: "Discover Your Routine", trust: ["Authentic Korean Brands", "Real Skincare Benefits", "Curated with Trust"] },
    featured: { eyebrow: "Featured Brands", heading: "Carefully selected Korean skincare,", headingEnd: "trusted by our team.", description: "Every brand inside HanaPure has been chosen because we genuinely believe in its quality, philosophy, and skincare benefits.", discover: "Discover Brand", roundLab: { tagline: "Hydration Specialist", description: "Gentle skincare inspired by clean Korean ingredients and daily hydration." }, anua: { tagline: "Calm Daily Care", description: "Minimal formulas focused on soothing, balancing, and supporting sensitive skin." }, skin1004: { tagline: "Centella Expert", description: "Known for calming skincare centered around Madagascar Centella." } },
    why: { eyebrow: "Why HanaPure", heading: "A bridge between Korean skincare and European customers.", description: "HanaPure combines Korean skincare knowledge with a customer-first perspective — helping you discover products that are authentic, effective, and carefully selected.", points: [{ title: "Perspective", description: "Created with a deep understanding of what skincare customers truly need." }, { title: "Korean Expertise", description: "Built on years of experience importing and selecting trusted Korean skincare for European customers." }, { title: "Carefully Curated", description: "We believe quality is more valuable than quantity. Every product in HanaPure is carefully chosen because we genuinely trust it." }] },
    brands: { eyebrow: "HanaPure directory", heading: "Explore our brands.", description: "A considered selection of Korean skincare names, gathered in one place for easy discovery.", seoDescription: "Explore Korean skincare brands in the HanaPure directory." },
    directory: { browse: "Browse brands", searchLabel: "Search by brand name", searchPlaceholder: "Search brands", filterLabel: "Filter brands by first letter", alphabet: "Browse A–Z", all: "All", resultOne: "{count} brand found", resultMany: "{count} brands found", empty: "No brands found", emptyDescription: "Try another name or choose All to browse every brand." },
  },
  hu: {
    hero: { eyebrow: "Megbízható koreai bőrápolás", heading: "Érezze magát magabiztosan a bőrében.", description: "Magyarországról indulva, Európában növekedve — a HanaPure gondosan válogatja az eredeti koreai bőrápolási termékeket, valódi bőrápolási előnyökkel és megbízható útmutatással.", shop: "Koreai bőrápolási termékek", routine: "Fedezze fel bőrápolási rutinját", trust: ["Eredeti koreai márkák", "Valódi bőrápolási előnyök", "Bizalommal válogatva"] },
    featured: { eyebrow: "Kiemelt márkák", heading: "Gondosan válogatott koreai bőrápolás,", headingEnd: "csapatunk bizalmával.", description: "A HanaPure minden márkáját azért választottuk, mert őszintén hiszünk a minőségében, szemléletében és bőrápolási előnyeiben.", discover: "Fedezze fel a márkát", roundLab: { tagline: "A hidratálás specialistája", description: "Gyengéd bőrápolás, amelyet tiszta koreai összetevők és a mindennapi hidratálás ihlettek." }, anua: { tagline: "Nyugodt mindennapi ápolás", description: "Egyszerű formulák, amelyek az érzékeny bőr megnyugtatására, egyensúlyára és támogatására összpontosítanak." }, skin1004: { tagline: "A Centella szakértője", description: "A madagaszkári Centellára épülő, nyugtató bőrápolásáról ismert." } },
    why: { eyebrow: "Miért a HanaPure?", heading: "Híd a koreai bőrápolás és az európai vásárlók között.", description: "A HanaPure a koreai bőrápolási ismereteket vásárlóközpontú szemlélettel ötvözi — segítve az eredeti, hatékony és gondosan válogatott termékek felfedezését.", points: [{ title: "Szemlélet", description: "A bőrápolási termékeket vásárlók valódi igényeinek mély megértésével jött létre." }, { title: "Koreai szakértelem", description: "Az európai vásárlóknak szánt, megbízható koreai bőrápolási termékek importjában és kiválasztásában szerzett többéves tapasztalatra épül." }, { title: "Gondosan válogatva", description: "Hiszünk abban, hogy a minőség értékesebb a mennyiségnél. A HanaPure minden termékét gondosan választjuk ki, mert őszintén megbízunk benne." }] },
    brands: { eyebrow: "HanaPure márkajegyzék", heading: "Fedezze fel márkáinkat.", description: "Koreai bőrápolási márkák átgondolt válogatása, egy helyen a könnyű felfedezésért.", seoDescription: "Fedezze fel a koreai bőrápolási márkákat a HanaPure márkajegyzékében." },
    directory: { browse: "Márkák böngészése", searchLabel: "Keresés márkanév alapján", searchPlaceholder: "Márkák keresése", filterLabel: "Márkák szűrése kezdőbetű szerint", alphabet: "Böngészés A–Z", all: "Mind", resultOne: "{count} márka található", resultMany: "{count} márka található", empty: "Nem található márka", emptyDescription: "Próbáljon másik nevet, vagy válassza a Mind lehetőséget az összes márka böngészéséhez." },
  },
  ko: {
    hero: { eyebrow: "믿을 수 있는 한국 스킨케어", heading: "피부에 자신감을 느껴보세요.", description: "헝가리에서 시작해 유럽으로 성장하는 HanaPure는 실제 피부 관리 효과와 믿을 수 있는 안내를 바탕으로 정품 한국 스킨케어를 신중하게 선택합니다.", shop: "한국 스킨케어 쇼핑", routine: "나의 스킨케어 루틴 알아보기", trust: ["정품 한국 브랜드", "실제 피부 관리 효과", "신뢰를 바탕으로 한 선택"] },
    featured: { eyebrow: "주목할 브랜드", heading: "신중하게 선택한 한국 스킨케어,", headingEnd: "우리 팀이 신뢰합니다.", description: "HanaPure의 모든 브랜드는 품질, 철학, 피부 관리 효과에 대한 진심 어린 믿음을 바탕으로 선택했습니다.", discover: "브랜드 알아보기", roundLab: { tagline: "보습 전문가", description: "깨끗한 한국 원료와 일상적인 보습에서 영감을 받은 순한 스킨케어입니다." }, anua: { tagline: "편안한 데일리 케어", description: "민감한 피부를 진정시키고 균형을 맞추며 돕는 데 중점을 둔 간결한 처방입니다." }, skin1004: { tagline: "센텔라 전문가", description: "마다가스카르 센텔라를 중심으로 한 진정 스킨케어로 알려져 있습니다." } },
    why: { eyebrow: "왜 HanaPure인가요?", heading: "한국 스킨케어와 유럽 고객을 잇는 다리.", description: "HanaPure는 한국 스킨케어 지식과 고객 우선의 관점을 결합하여 정품이며 효과적이고 신중하게 선택된 제품을 발견할 수 있도록 돕습니다.", points: [{ title: "관점", description: "스킨케어 고객에게 진정으로 필요한 것을 깊이 이해하며 만들어졌습니다." }, { title: "한국 스킨케어 전문성", description: "유럽 고객을 위해 믿을 수 있는 한국 스킨케어를 수입하고 선택해 온 다년간의 경험을 바탕으로 합니다." }, { title: "신중한 선택", description: "우리는 양보다 질이 더 가치 있다고 믿습니다. HanaPure의 모든 제품은 진심으로 신뢰하기에 신중하게 선택합니다." }] },
    brands: { eyebrow: "HanaPure 브랜드 목록", heading: "브랜드를 살펴보세요.", description: "한국 스킨케어 브랜드를 신중하게 모아 한곳에서 쉽게 살펴볼 수 있습니다.", seoDescription: "HanaPure 브랜드 목록에서 한국 스킨케어 브랜드를 살펴보세요." },
    directory: { browse: "브랜드 둘러보기", searchLabel: "브랜드 이름으로 검색", searchPlaceholder: "브랜드 검색", filterLabel: "첫 글자로 브랜드 필터링", alphabet: "A–Z 둘러보기", all: "전체", resultOne: "브랜드 {count}개 찾음", resultMany: "브랜드 {count}개 찾음", empty: "브랜드를 찾을 수 없습니다", emptyDescription: "다른 이름으로 검색하거나 전체를 선택해 모든 브랜드를 살펴보세요." },
  },
} satisfies Record<EditorialLocale, MarketingCopy>;

export type MarketingCopy = {
  hero: { eyebrow: string; heading: string; description: string; shop: string; routine: string; trust: string[] };
  featured: { eyebrow: string; heading: string; headingEnd: string; description: string; discover: string; roundLab: BrandCopy; anua: BrandCopy; skin1004: BrandCopy };
  why: { eyebrow: string; heading: string; description: string; points: { title: string; description: string }[] };
  brands: { eyebrow: string; heading: string; description: string; seoDescription: string };
  directory: { browse: string; searchLabel: string; searchPlaceholder: string; filterLabel: string; alphabet: string; all: string; resultOne: string; resultMany: string; empty: string; emptyDescription: string };
};
type BrandCopy = { tagline: string; description: string };
